bsp_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings

from django.conf.urls.static import static

urlpatterns = [
    url(r'^home/', include('home_page.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('shopify_auth.urls')),
    url(r'^pages/', include('pages.urls')),
]

urlpatterns += staticfiles_urlpatterns()

home_page/urls.py
from django.conf.urls import url
from . import views

app_name = 'home_page'

urlpatterns = [
    url(r'^', views.home),
]

pages/urls.py
from django.conf.urls import url
from . import views

app_name = 'pages'

urlpatterns = [
    url(r'^create/$', views.page_create, name='create'),
    url(r'^list/$', views.page_list, name='list'),
    url(r'^edit/(?P<header_title>.*)/$', views.page_edit, name='edit'),
    url(r'^preview/(?P<shop>.*)/(?P<header_title>.*)/$', views.page_preview, name='preview'),
    url(r'^upload_image', views.upload_image),
]

home_page/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.q
from shopify_auth.models import AbstractShopUser


class AuthAppShopUser(AbstractShopUser):
    pass

home_page/views.py
from django.shortcuts import render

# Create your views here.

from shopify_auth.decorators import login_required
from django.shortcuts import redirect, render
from config import Config
import shopify

shopify.Session.setup(**Config.authen_params)


def copy_template():
    shopify.Asset.create({
        'key': Config.theme_params['templates'],
        'value': open('assets/templates/page.%s.liquid' % Config.prefix).read()
    })

    shopify.Asset.create({
        'key': Config.theme_params['layout'],
        'value': open('assets/templates/theme.%s.liquid' % Config.prefix).read()
    })


def install_template(request):
    try:
        theme = shopify.Theme().find(role='main')[0]
        shopify.Asset().find(Config.theme_params['templates'], theme_id=theme.id)
    except Exception as e:
        print('%s: copying template ...', e)
        copy_template()


@login_required
def home(request, *args, **kwargs):
    with request.user.session:
        install_template(request)
        return render(request, "index.html")

home_page/templates/error.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Error</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Looks like something went wrong. <small></small></h1>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>

home_page/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome</title>
</head>
<body style="margin: 0 auto; padding:20%;">
<h1>Welcome Best Sales Page New!</h1>
<li>
    <a href="{% url 'pages:create' %}"> Create new page </a>
</li>
<li>
    <a href="{% url 'pages:list' %}"> List all pages </a>
</li>
</body>
<script type="text/javascript" src="https://cdn.shopify.com/s/assets/external/app.js"></script>
<script type="text/javascript">
    ShopifyApp.init({
        apiKey: '{{ SHOPIFY_APP_API_KEY }}',
        shopOrigin: 'https://{{ user.myshopify_domain }}'
    });
    ShopifyApp.ready(function () {
        ShopifyApp.Bar.initialize({
            title: '{{ SHOPIFY_APP_NAME }}',
            buttons: {}
        });
    });
</script>
</html>

home_page/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome</title>
  </head>
  <body style="margin: 0 auto; padding:20%;">
    <h1>Welcome Best Sales Page!</h1>
    <a href="{% url 'pages:create' %}"> Create new page </a>
  </body>
</html>